//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEmployee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEmployee()
        {
            this.tblRequestForChanges = new HashSet<tblRequestForChange>();
        }
    
        public int EmployeeId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> WorkExperience { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public string EducationDegree { get; set; }
        public Nullable<int> SuperiorManagerId { get; set; }
    
        public virtual tblPosition tblPosition { get; set; }
        public virtual tblSector tblSector { get; set; }
        public virtual tblManager tblManager { get; set; }
        public virtual tblUser tblUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblRequestForChange> tblRequestForChanges { get; set; }
    }
}
