//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRequestForChange
    {
        public int RequestId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> NewSectorId { get; set; }
        public Nullable<int> NewPositionId { get; set; }
        public Nullable<int> NewWorkExperience { get; set; }
        public string NewEducationDegree { get; set; }
        public Nullable<System.DateTime> DateAndTimeOfCreation { get; set; }
        public string Status { get; set; }
    
        public virtual tblEmployee tblEmployee { get; set; }
        public virtual tblPosition tblPosition { get; set; }
        public virtual tblSector tblSector { get; set; }
    }
}
