//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int UserId { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string JMBG { get; set; }
        public string Gender { get; set; }
        public string Residence { get; set; }
        public string MarriageStatus { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public string EducationDegree { get; set; }
        public Nullable<decimal> Salary { get; set; }
        public Nullable<int> WorkExperience { get; set; }
        public string PositionName { get; set; }
        public string PositionDescription { get; set; }
        public string SectorName { get; set; }
        public string SectorDescription { get; set; }
        public int SectorId { get; set; }
        public Nullable<int> SuperiorManagerId { get; set; }
    }
}
