//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwRequestForChange
    {
        public int RequestId { get; set; }
        public int EmployeeId { get; set; }
        public Nullable<int> NewSectorId { get; set; }
        public Nullable<int> NewPositionId { get; set; }
        public Nullable<int> NewWorkExperience { get; set; }
        public string NewEducationDegree { get; set; }
        public Nullable<System.DateTime> DateAndTimeOfCreation { get; set; }
        public string Status { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> WorkExperience { get; set; }
        public string EducationDegree { get; set; }
        public string SectorName { get; set; }
        public string PositionName { get; set; }
        public Nullable<int> SuperiorManagerId { get; set; }
        public string Employee { get; set; }
    }
}
